/**
 * HISTORICAL REFERENCE — not the runtime source of truth.
 *
 * These entries were transcribed into `database/seeders/ProjectSeeder.php` and
 * now live in the `projects` table, edited through /admin/projects. The pages
 * receive them as Inertia props. The `Project` typedef below is still imported
 * for JSDoc types, so keep it in sync with `Project::toPublicArray()`.
 */

/**
 * Real Marketorr work, sourced from marketorr.com (case studies + portfolio).
 * Cover images live in `public/images/work/`.
 *
 * @typedef {{
 *   slug: string,
 *   title: string,
 *   client: string,
 *   category: string,
 *   year: string,
 *   description: string,
 *   tags: string[],
 *   accent: string,
 *   image: string,
 *   imageAlt: string,
 *   metric?: string,
 *   metricLabel?: string,
 *   featured?: boolean,
 * }} Project
 */

/** @type {Project[]} */
export const PROJECTS = [
    {
        slug: 'imperial-jute-b2b-seo',
        title: 'Imperial Jute',
        client: 'Imperial Jute · Jute Goods Manufacturer',
        category: 'B2B SEO · Content Strategy',
        year: '2023',
        description:
            'An SEO overhaul for a jute goods manufacturer and exporter: website UI redesign, industry keyword research and a content-first strategy that put 200+ keywords on page one in six months — without a backlink strategy.',
        metric: '2100%',
        metricLabel: 'Organic Traffic Increase',
        accent: '#891FFB',
        image: '/images/work/imperial-jute-logo.webp',
        imageAlt: 'Imperial Jute 3D logo animation',
        tags: ['SEO', 'Content Strategy', 'Web UI/UX'],
        featured: true,
    },
    {
        slug: 'charukothon-meta-ads',
        title: 'Charukothon',
        client: 'Charukothon · Fashion Brand, Bangladesh',
        category: 'Paid Ads · Creative Strategy',
        year: '2026',
        description:
            'A creative-first Meta ads launch for a brand-new Bangladeshi fashion label: a custom photo and video frame system, one exclusive influencer partnership and collage-style single-image testing took the page from zero to 1 million BDT in monthly revenue in 60 days.',
        metric: '11X',
        metricLabel: 'Return on Ad Spend',
        accent: '#891FFB',
        image: '/images/work/charukothon-meta-ads.webp',
        imageAlt: 'Charukothon fashion brand Meta ads case study cover',
        tags: ['Paid Ads', 'Creative Strategy', 'Growth'],
        featured: true,
    },
    {
        slug: 'all-city-duct-cleaning-ads',
        title: 'All City Duct Cleaning',
        client: 'All City Duct Cleaning · 7 US States',
        category: 'Paid Ads · Facebook Campaigns',
        year: '2023',
        description:
            'A three-phase Facebook ad strategy — segmented audiences with video, carousel and static creative — generated 1,379 messages from $19,397 of spend and lifted average order value from $270 to $450.',
        metric: '60.37%',
        metricLabel: 'Conversion Rate',
        accent: '#1BE2EB',
        image: '/images/work/all-city-duct-cleaning-ads.jpg',
        imageAlt: 'All City Duct Cleaning Facebook ads case study cover',
        tags: ['Paid Ads', 'Campaign', 'Lead Gen'],
        featured: true,
    },
    {
        slug: 'city-online-brand-design',
        title: 'City Online',
        client: 'City Online Limited',
        category: 'Brand Design · Identity Guidelines',
        year: '2023',
        description: 'City Online brand identity design — a complete mark, palette and guideline system for an internet service provider.',
        accent: '#891FFB',
        image: '/images/work/city-online-brand.jpg',
        imageAlt: 'City Online brand identity design',
        tags: ['Branding', 'Identity Guidelines'],
        featured: true,
    },
    {
        slug: 'city-online-web',
        title: 'City Online Limited',
        client: 'City Online Limited',
        category: 'Web UI/UX · Development',
        year: '2024',
        description: 'UI/UX design and website development for City Online Limited, carrying the new identity into a live service platform.',
        accent: '#507AF4',
        image: '/images/work/city-online-web.jpg',
        imageAlt: 'City Online Limited website design',
        tags: ['Web UI/UX', 'Development'],
    },
    {
        slug: 'dusty-vision',
        title: 'Dusty Vision',
        client: 'Dusty Vision · Home Improvement',
        category: 'Brand Design · Visual Identity',
        year: '2023',
        description: 'Logo and visual identity design for a home improvement brand.',
        accent: '#1BE2EB',
        image: '/images/work/dusty-vision.jpg',
        imageAlt: 'Dusty Vision logo and visual identity design',
        tags: ['Branding', 'Logo Design'],
    },
    {
        slug: 'virgin-trend',
        title: 'Virgin Trend',
        client: 'Virgin Trend · Fashion',
        category: 'Brand Design · Fashion',
        year: '2023',
        description: 'Logo and brand design portfolio for a clothing brand.',
        accent: '#891FFB',
        image: '/images/work/virgin-trend.jpg',
        imageAlt: 'Virgin Trend fashion brand visual identity design',
        tags: ['Branding', 'Visual Identity'],
    },
    {
        slug: 'imperial-jute-brand-design',
        title: 'Imperial Jute Brand',
        client: 'Imperial Jute',
        category: 'Brand Design · Minimal Logo',
        year: '2023',
        description: 'Minimal logo and brand design for a jute company, built to travel from export packaging to the web.',
        accent: '#507AF4',
        image: '/images/work/imperial-jute-brand.jpg',
        imageAlt: 'Imperial Jute minimal logo and brand design',
        tags: ['Branding', 'Logo Design'],
    },
    {
        slug: 'un-point-brand-design',
        title: 'Un-Point',
        client: 'Un-Point · Engineering Consulting',
        category: 'Brand Design · Engineering',
        year: '2023',
        description: 'Visual brand identity design portfolio for an engineering consulting firm.',
        accent: '#1BE2EB',
        image: '/images/work/un-point.jpg',
        imageAlt: 'Un-Point engineering consulting firm visual identity design',
        tags: ['Branding', 'Visual Identity'],
    },
    {
        slug: 'nature-to-near',
        title: 'Nature to Near',
        client: 'NTBT · Agro Firm',
        category: 'Brand Design · Agro',
        year: '2023',
        description: 'Logo, branding and visual identity for an agro firm — a warm, grounded system for produce and packaging.',
        accent: '#891FFB',
        image: '/images/work/nature-to-near.jpg',
        imageAlt: 'Nature to Near agro firm logo and branding',
        tags: ['Branding', 'Packaging'],
    },
    {
        slug: 'sabdita-fashion',
        title: 'Sabdita Fashion',
        client: 'Sabdita Fashion',
        category: 'Brand Design · Packaging',
        year: '2024',
        description: 'Logo, packaging and visual identity design for the fashion industry.',
        accent: '#507AF4',
        image: '/images/work/sabdita-fashion.jpg',
        imageAlt: 'Sabdita Fashion logo, packaging and visual identity design',
        tags: ['Branding', 'Packaging'],
    },
    {
        slug: 'animateuix-brand-design',
        title: 'AnimateUIX',
        client: 'AnimateUIX',
        category: 'Brand Design · Product',
        year: '2024',
        description: 'AnimateUIX brand design — a logo presentation system for a motion-led product studio.',
        accent: '#1BE2EB',
        image: '/images/work/animateuix.jpg',
        imageAlt: 'AnimateUIX brand and logo design',
        tags: ['Branding', 'Logo Design'],
    },
    {
        slug: 'ecohub-essentials',
        title: 'EcoHub Essentials',
        client: 'EcoHub Essentials · E-commerce',
        category: 'Web Development · E-commerce',
        year: '2024',
        description: 'Web development project for an electronic online store, built for catalogue depth and fast checkout.',
        accent: '#891FFB',
        image: '/images/work/ecohub-essentials.jpg',
        imageAlt: 'EcoHub Essentials e-commerce website',
        tags: ['Web UI/UX', 'E-commerce'],
    },
    {
        slug: 'photo-fix-zone',
        title: 'Photo Fix Zone',
        client: 'Photo Fix Zone · Image Editing',
        category: 'Web Development · Service Site',
        year: '2024',
        description: 'Web development project for an image editing firm, structured around service clarity and quote requests.',
        accent: '#507AF4',
        image: '/images/work/photo-fix-zone.jpg',
        imageAlt: 'Photo Fix Zone website design',
        tags: ['Web UI/UX', 'Development'],
    },
];

/** The four projects the home page's Our Work section leads with. */
export const FEATURED_PROJECTS = PROJECTS.filter((p) => p.featured);
